apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: {{ .Chart.Name | lower }}-secrets
data:
  accounts.nats.pass: {{ required "global.accounts.nats.pass is required" .Values.global.accounts.nats.pass | b64enc | quote }}
  accounts.nats.user: {{ required "global.accounts.nats.user is required" .Values.global.accounts.nats.user | b64enc | quote }}
  bootstrap-cert.pem: {{ required "global.certs.bootstrap.cert is required" .Values.global.certs.bootstrap.cert | quote }}
  bootstrap-key.pass: {{ required "global.certs.bootstrap.pass is required" .Values.global.certs.bootstrap.pass | b64enc | quote }}
  bootstrap-key.pem: {{ required "global.certs.bootstrap.key is required" .Values.global.certs.bootstrap.key | quote }}
  ca-chain-system.pem: {{ required "global.certs.ca.system.chain is required" .Values.global.certs.ca.system.chain | quote }}
